apiVersion: batch/v1
kind: Job
metadata:
  name: user
spec:
  template:
    metadata:
      name: user
    spec:
      containers:
        - name: postgres-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_PASSWORD
          command:
            - sh
            - -c
            - psql postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB --command "create table users (id bigserial primary key, username varchar, first_name varchar, last_name varchar, email varchar, phone varchar)"
      restartPolicy: OnFailure
  backoffLimit: 0